import TwinPrimeExternal.RecursiveMPPMCertificate

/-!
# Generated Recursive MP/PM Certificate

Generated by `tools/generate_external_certificate.cpp`.

Lean checks the displayed arithmetic and the finite-set contradiction.  The
external C++ certificate boundary is now the route-realization bridge: under a
cofinal exceptional tail, every generated predicted MP/PM event is realized as
an actual generated MP/PM event.
-/

namespace TwinPrimeExternal.GeneratedCertificate

def firstOverflowPrime : Nat := 191281
def firstOverflowSpan : Nat := 17
def firstOverflowSplitPrimes : Nat := 1
def firstOverflowRoutedStarts : Nat := 1
def E_a : Nat := 95568
def E_p : Nat := 181052
def falsePredictedEventCount : Nat := 115633

theorem E_a_eq_cap :
    E_a = TwinPrimeExternal.generatedMPPMCard := by
  norm_num [E_a, TwinPrimeExternal.generatedMPPMCard]

theorem E_p_eq_core :
    E_p =
      TwinPrimeExternal.predictedEventCount := by
  norm_num [E_p,
    TwinPrimeExternal.predictedEventCount]

theorem E_p_exceeds_E_a :
    E_a < E_p := by
  norm_num [E_a, E_p]

theorem core_predictedEventCount_exceeds_generatedMPPMCard :
    TwinPrimeExternal.generatedMPPMCard <
      TwinPrimeExternal.predictedEventCount := by
  simpa [E_a_eq_cap, E_p_eq_core] using E_p_exceeds_E_a

/--
The actual finite side-labeled MP/PM event set, represented only by its
generated count.  The C++ audit owns the concrete decoded event list.
-/
def actualEvents : Finset Nat := Finset.range E_a

theorem actualEvents_card :
    actualEvents.card = TwinPrimeExternal.generatedMPPMCard := by
  rw [actualEvents, E_a_eq_cap]
  simp

/--
The generated predicted side-labeled MP/PM event set, represented only by its
generated unique-event count.  The C++ audit owns the concrete decoded event
list and recursive closure computation.
-/
def predictedEvents : Finset Nat := Finset.range E_p

theorem predictedEvents_card :
    predictedEvents.card = TwinPrimeExternal.predictedEventCount := by
  rw [predictedEvents, E_p_eq_core]
  simp

/--
Route-realization bridge required by this generated count certificate.

If supplied as a checked Lean theorem, it says that if a cofinal exceptional
tail existed, every unique predicted MP/PM event produced by the recursive
descent would be an actual event in the generated finite target block.
-/
def GeneratedRouteRealization : Prop :=
    (exists B,
      TwinPrimeExternal.CofinalExceptionTail
        TwinPrimeExternal.MidpointExceptionalPrime B) ->
      predictedEvents ⊆ actualEvents

def recursiveMPPMEventCertificate
    (realized : GeneratedRouteRealization) :
    TwinPrimeExternal.RecursiveMPPMEventCertificate where
  actualEvents := actualEvents
  predictedEvents := predictedEvents
  actual_card := actualEvents_card
  predicted_card := predictedEvents_card
  predicted_realized_of_cofinalTail := realized

/--
No cofinal exceptional tail, derived inside Lean from the recursive MP/PM event
certificate and the checked cardinal arithmetic `95568 < 181052`.
-/
theorem no_cofinalExceptionTail
    (realized : GeneratedRouteRealization) :
    Not (exists B,
      TwinPrimeExternal.CofinalExceptionTail
        TwinPrimeExternal.MidpointExceptionalPrime B) :=
  TwinPrimeExternal.no_cofinalExceptionTail_of_recursiveMPPMEventCertificate
    (recursiveMPPMEventCertificate realized)

end TwinPrimeExternal.GeneratedCertificate
