import TwinPrimeExternal.FixedGap

/-!
# Generated Fixed-Gap Certificates

Generated by `tools/generate_fixed_gap_certificates.cpp`.

This file records finite midpoint-row scans for the Pythagorean fixed-gap
candidates up to actual gap `246`.  The finite scan only proves that the
first fixed-gap exception after `127`, if any, is beyond the checked window.
The full infinitude endpoint for a fixed gap still requires the corresponding
external recursive no-tail certificate.
-/

namespace TwinPrimeExternal.GeneratedFixedGapCertificates

def last : Nat := 127
def checkedTo : Nat := 191264

theorem checkedTo_eq_certificateVerifiedTo :
    checkedTo = TwinPrimeExternal.certificateVerifiedTo := by
  norm_num [checkedTo, TwinPrimeExternal.certificateVerifiedTo]

namespace gap12

def d : Nat := 6
def actualGap : Nat := 12
def A : Nat := 3
def B : Nat := 4
def C : Nat := 5
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 1703

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap12

namespace gap48

def d : Nat := 24
def actualGap : Nat := 48
def A : Nat := 6
def B : Nat := 8
def C : Nat := 10
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 2227

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap48

namespace gap60

def d : Nat := 30
def actualGap : Nat := 60
def A : Nat := 5
def B : Nat := 12
def C : Nat := 13
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 917

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap60

namespace gap108

def d : Nat := 54
def actualGap : Nat := 108
def A : Nat := 9
def B : Nat := 12
def C : Nat := 15
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 655

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap108

namespace gap120

def d : Nat := 60
def actualGap : Nat := 120
def A : Nat := 8
def B : Nat := 15
def C : Nat := 17
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 131

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap120

namespace gap168

def d : Nat := 84
def actualGap : Nat := 168
def A : Nat := 7
def B : Nat := 24
def C : Nat := 25
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 655

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap168

namespace gap192

def d : Nat := 96
def actualGap : Nat := 192
def A : Nat := 12
def B : Nat := 16
def C : Nat := 20
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 917

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap192

namespace gap240

def d : Nat := 120
def actualGap : Nat := 240
def A : Nat := 10
def B : Nat := 24
def C : Nat := 26
def checkedPrimeRoots : Nat := 17236
def survivorRows : Nat := 17236
def failedRoots : Nat := 0
def firstWitnessAfterLast : Nat := 1703

theorem pythagorean_family :
    A * B = 2 * d /\ A ^ 2 + B ^ 2 = C ^ 2 := by
  norm_num [A, B, C, d]

theorem actualGap_eq : actualGap = 2 * d := by
  norm_num [actualGap, d]

theorem actualGap_le_246 : actualGap <= 246 := by
  norm_num [actualGap]

theorem failedRoots_eq_zero : failedRoots = 0 := by
  rfl

/-- Lean proposition represented by the generated finite scan for this fixed gap. -/
def ExceptionFreeCertificate : Prop :=
    TwinPrimeExternal.ExceptionFreeUpTo
      (TwinPrimeExternal.FixedGapExceptionalPrime d)
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (free : ExceptionFreeCertificate)
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        (TwinPrimeExternal.FixedGapExceptionalPrime d)) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    free firstException

/--
Total fixed-gap endpoint status for this candidate.  This theorem is
conditional until a recursive no-cofinal-tail certificate is generated for
this exact fixed gap.
-/
theorem arbitrarily_large_pairs_of_no_tail
    (hno :
      Not (exists K,
        TwinPrimeExternal.CofinalExceptionTail
          (TwinPrimeExternal.FixedGapExceptionalPrime d) K)) :
    TwinPrimeExternal.ArbitrarilyLargeFixedGapPrimePairs d :=
  TwinPrimeExternal.arbitrarily_large_fixedGapPairs_of_no_cofinalExceptionTail
    hno

end gap240

end TwinPrimeExternal.GeneratedFixedGapCertificates

