import TwinPrimeExternal.Core

/-!
# Generated Gap Certificate

Generated by `tools/check_cone_survivor_gap.cpp`.

It records the external finite check that every prime in `(127, 191264]` has a
midpoint-row twin witness, so the first exception after 127 cannot occur before
the certificate threshold.
-/

namespace TwinPrimeExternal.GeneratedGapCertificate

def gapLast : Nat := 127
def gapCheckedTo : Nat := 191264
def gapSize : Nat := 191137
def checkedPrimes : Nat := 17236
def failedPrimes : Nat := 0

theorem gapLast_eq_lastObservedException :
    gapLast = TwinPrimeExternal.lastObservedException := by
  norm_num [gapLast, TwinPrimeExternal.lastObservedException]

theorem gapCheckedTo_eq_certificateVerifiedTo :
    gapCheckedTo = TwinPrimeExternal.certificateVerifiedTo := by
  norm_num [gapCheckedTo, TwinPrimeExternal.certificateVerifiedTo]

theorem failedPrimes_eq_zero :
    failedPrimes = 0 := by
  rfl

/--
Trusted external C++ gap certificate.

The checker found a midpoint-row twin witness for every prime
`127 < r <= 191264`, so no such prime is midpoint-exceptional.
-/
axiom external_exceptionFree_to_certificateThreshold :
    TwinPrimeExternal.ExceptionFreeUpTo
      TwinPrimeExternal.MidpointExceptionalPrime
      TwinPrimeExternal.certificateVerifiedTo

theorem any_firstException_after_127_occurs_after_certificateThreshold
    (firstException :
      TwinPrimeExternal.FirstExceptionAfterLastObserved
        TwinPrimeExternal.MidpointExceptionalPrime) :
    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=
  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo
    external_exceptionFree_to_certificateThreshold firstException

end TwinPrimeExternal.GeneratedGapCertificate
