import TwinPrimeCertificate.Core
import TwinPrimeCertificate.RecursiveMPPMCertificate
import TwinPrimeCertificate.DescentPressure
import TwinPrimeCertificate.QuadraticRootSupply
import TwinPrimeCertificate.FiniteSinkAvoidance
import TwinPrimeCertificate.TailInductionCertificate
import TwinPrimeCertificate.Final
import TwinPrimeCertificate.UniqueDescentEndpoint

