#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

using u64 = unsigned long long;
using u128 = unsigned __int128;

namespace {

struct Options {
  u64 last = 127;
  u64 checked_to = 191264;
  bool print_rows = false;
  std::string json_out;
  std::string lean_out = "TwinPrimeExternal/GeneratedGapCertificate.lean";
};

u64 parse_u64(const std::string &s, const std::string &name) {
  std::size_t pos = 0;
  const u64 value = std::stoull(s, &pos);
  if (pos != s.size()) {
    throw std::runtime_error("invalid integer for " + name + ": " + s);
  }
  return value;
}

std::vector<u64> primes_upto(u64 n) {
  std::vector<bool> composite(n + 1, false);
  std::vector<u64> primes;
  for (u64 p = 2; p <= n; ++p) {
    if (composite[p]) {
      continue;
    }
    primes.push_back(p);
    if (p <= n / p) {
      for (u64 m = p * p; m <= n; m += p) {
        composite[m] = true;
      }
    }
  }
  return primes;
}

bool cone_survives(u64 r, u64 h, const std::vector<u64> &primes) {
  const u128 center = static_cast<u128>(r) * h;
  const u128 minus_value = center - 1;
  const u128 plus_value = center + 1;
  for (u64 q : primes) {
    if (q >= r) {
      break;
    }
    if (minus_value % q == 0 || plus_value % q == 0) {
      return false;
    }
  }
  return true;
}

bool find_survivor(u64 r, const std::vector<u64> &primes, u64 &h_out) {
  if (r <= 3) {
    return false;
  }

  // For odd primes r > 3, any twin-witness index h must be divisible by 2 and 3:
  // otherwise one of r*h-1 or r*h+1 is divisible by 2 or 3.
  for (u64 h = 6; h < r; h += 6) {
    if (cone_survives(r, h, primes)) {
      h_out = h;
      return true;
    }
  }
  return false;
}

struct Row {
  u64 r;
  u64 h;
};

struct Result {
  std::vector<Row> rows;
  std::vector<u64> failed;
  u64 checked_prime_roots = 0;
};

Result run_check(const Options &opt) {
  if (opt.last >= opt.checked_to) {
    throw std::runtime_error("--checked-to must be greater than --last");
  }
  const auto primes = primes_upto(opt.checked_to);
  Result result;
  for (u64 r : primes) {
    if (r <= opt.last || opt.checked_to < r) {
      continue;
    }
    ++result.checked_prime_roots;
    u64 h = 0;
    if (find_survivor(r, primes, h)) {
      result.rows.push_back({r, h});
    } else {
      result.failed.push_back(r);
    }
  }
  return result;
}

void write_json(std::ostream &out, const Options &opt, const Result &result) {
  out << "{\n";
  out << "  \"mode\": \"cone-survivor-gap\",\n";
  out << "  \"last\": " << opt.last << ",\n";
  out << "  \"checkedTo\": " << opt.checked_to << ",\n";
  out << "  \"gapSize\": " << (opt.checked_to - opt.last) << ",\n";
  out << "  \"checkedPrimeRoots\": " << result.checked_prime_roots << ",\n";
  out << "  \"survivorRows\": " << result.rows.size() << ",\n";
  out << "  \"failedRoots\": [";
  for (std::size_t i = 0; i < result.failed.size(); ++i) {
    if (i != 0) {
      out << ", ";
    }
    out << result.failed[i];
  }
  out << "],\n";
  out << "  \"success\": " << (result.failed.empty() ? "true" : "false");
  if (opt.print_rows) {
    out << ",\n  \"rows\": [\n";
    for (std::size_t i = 0; i < result.rows.size(); ++i) {
      out << "    {\"r\": " << result.rows[i].r
          << ", \"h\": " << result.rows[i].h << "}";
      if (i + 1 != result.rows.size()) {
        out << ",";
      }
      out << "\n";
    }
    out << "  ]\n";
  } else {
    out << "\n";
  }
  out << "}\n";
}

void write_lean(std::ostream &out, const Options &opt, const Result &result) {
  out << "import TwinPrimeExternal.Core\n\n";
  out << "/-!\n";
  out << "# Generated Gap Certificate\n\n";
  out << "Generated by `tools/check_cone_survivor_gap.cpp`.\n\n";
  out << "It records the external finite check that every prime in `(127, 191264]` has a\n";
  out << "midpoint-row twin witness, so the first exception after 127 cannot occur before\n";
  out << "the certificate threshold.\n";
  out << "-/\n\n";
  out << "namespace TwinPrimeExternal.GeneratedGapCertificate\n\n";
  out << "def gapLast : Nat := " << opt.last << "\n";
  out << "def gapCheckedTo : Nat := " << opt.checked_to << "\n";
  out << "def gapSize : Nat := " << (opt.checked_to - opt.last) << "\n";
  out << "def checkedPrimes : Nat := " << result.checked_prime_roots << "\n";
  out << "def failedPrimes : Nat := " << result.failed.size() << "\n\n";
  out << "theorem gapLast_eq_lastObservedException :\n";
  out << "    gapLast = TwinPrimeExternal.lastObservedException := by\n";
  out << "  norm_num [gapLast, TwinPrimeExternal.lastObservedException]\n\n";
  out << "theorem gapCheckedTo_eq_certificateVerifiedTo :\n";
  out << "    gapCheckedTo = TwinPrimeExternal.certificateVerifiedTo := by\n";
  out << "  norm_num [gapCheckedTo, TwinPrimeExternal.certificateVerifiedTo]\n\n";
  out << "theorem failedPrimes_eq_zero :\n";
  out << "    failedPrimes = 0 := by\n";
  out << "  rfl\n\n";
  out << "/--\n";
  out << "Trusted external C++ gap certificate.\n\n";
  out << "The checker found a midpoint-row twin witness for every prime\n";
  out << "`127 < r <= 191264`, so no such prime is midpoint-exceptional.\n";
  out << "-/\n";
  out << "axiom external_exceptionFree_to_certificateThreshold :\n";
  out << "    TwinPrimeExternal.ExceptionFreeUpTo\n";
  out << "      TwinPrimeExternal.MidpointExceptionalPrime\n";
  out << "      TwinPrimeExternal.certificateVerifiedTo\n\n";
  out << "theorem any_firstException_after_127_occurs_after_certificateThreshold\n";
  out << "    (firstException :\n";
  out << "      TwinPrimeExternal.FirstExceptionAfterLastObserved\n";
  out << "        TwinPrimeExternal.MidpointExceptionalPrime) :\n";
  out << "    TwinPrimeExternal.certificateVerifiedTo < firstException.r :=\n";
  out << "  TwinPrimeExternal.firstExceptionAfterLast_occurs_after_certificateThreshold_of_exceptionFreeUpTo\n";
  out << "    external_exceptionFree_to_certificateThreshold firstException\n\n";
  out << "end TwinPrimeExternal.GeneratedGapCertificate\n";
}

Options parse_options(int argc, char **argv) {
  Options opt;
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    auto need = [&]() -> std::string {
      if (++i >= argc) {
        throw std::runtime_error("missing value after " + arg);
      }
      return argv[i];
    };
    if (arg == "--last") {
      opt.last = parse_u64(need(), arg);
    } else if (arg == "--checked-to") {
      opt.checked_to = parse_u64(need(), arg);
    } else if (arg == "--json-out") {
      opt.json_out = need();
    } else if (arg == "--lean-out") {
      opt.lean_out = need();
    } else if (arg == "--print-rows") {
      opt.print_rows = true;
    } else {
      throw std::runtime_error("unknown argument: " + arg);
    }
  }
  return opt;
}

}  // namespace

int main(int argc, char **argv) {
  try {
    const Options opt = parse_options(argc, argv);
    const Result result = run_check(opt);

    write_json(std::cout, opt, result);

    if (!opt.json_out.empty()) {
      std::ofstream json(opt.json_out);
      if (!json) {
        throw std::runtime_error("could not open JSON output");
      }
      write_json(json, opt, result);
    }
    if (!opt.lean_out.empty()) {
      std::ofstream lean(opt.lean_out);
      if (!lean) {
        throw std::runtime_error("could not open Lean output");
      }
      write_lean(lean, opt, result);
    }

    return result.failed.empty() ? 0 : 1;
  } catch (const std::exception &ex) {
    std::cerr << "error: " << ex.what() << "\n";
    return 2;
  }
}
