#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>

namespace {

struct Certificate {
  unsigned long long firstOverflowRoot = 191281;
  unsigned long long firstOverflowSpan = 17;
  unsigned long long firstOverflowSplitRoots = 1;
  unsigned long long firstOverflowRoutedStarts = 1;
  unsigned long long generatedActualEventCount = 95568;
  unsigned long long generatedPredictedEventCount = 181052;
  unsigned long long falsePredictedEventCount = 115633;
};

unsigned long long parse_json_scalar(const std::string &text, const std::string &key) {
  const std::string needle = "\"" + key + "\"";
  std::size_t pos = text.find(needle);
  if (pos == std::string::npos) {
    throw std::runtime_error("missing JSON key: " + key);
  }
  pos = text.find(':', pos);
  if (pos == std::string::npos) {
    throw std::runtime_error("missing ':' after JSON key: " + key);
  }
  while (pos < text.size() && (text[pos] < '0' || text[pos] > '9')) {
    ++pos;
  }
  if (pos == text.size()) {
    throw std::runtime_error("missing numeric value for JSON key: " + key);
  }
  unsigned long long value = 0;
  while (pos < text.size() && '0' <= text[pos] && text[pos] <= '9') {
    value = value * 10 + static_cast<unsigned long long>(text[pos] - '0');
    ++pos;
  }
  return value;
}

Certificate read_certificate_json(const std::string &path) {
  std::ifstream in(path);
  if (!in) {
    throw std::runtime_error("could not open JSON certificate: " + path);
  }
  const std::string text((std::istreambuf_iterator<char>(in)),
                         std::istreambuf_iterator<char>());
  Certificate c;
  c.firstOverflowRoot = parse_json_scalar(text, "firstOverflowRoot");
  c.firstOverflowSpan = parse_json_scalar(text, "firstOverflowSpan");
  c.firstOverflowSplitRoots = parse_json_scalar(text, "firstOverflowSplitRoots");
  c.firstOverflowRoutedStarts = parse_json_scalar(text, "firstOverflowRoutedStarts");
  c.generatedActualEventCount = parse_json_scalar(text, "generatedActualEventCount");
  if (text.find("\"generatedPredictedEventCount\"") != std::string::npos) {
    c.generatedPredictedEventCount =
        parse_json_scalar(text, "generatedPredictedEventCount");
  } else {
    c.generatedPredictedEventCount =
        parse_json_scalar(text, "predictedEventCount");
  }
  c.falsePredictedEventCount = parse_json_scalar(text, "falsePredictedEventCount");
  return c;
}

void write_lean(const std::string &path, const Certificate &c) {
  std::ofstream out(path);
  if (!out) {
    throw std::runtime_error("could not open Lean output: " + path);
  }

  out << "import TwinPrimeExternal.Core\n\n";
  out << "/-!\n";
  out << "# Generated External Certificate\n\n";
  out << "Generated by `tools/generate_external_certificate.cpp`.\n\n";
  out << "Lean checks the displayed arithmetic.  The cofinal-tail obstruction is\n";
  out << "the external C++ certificate boundary: the C++ search and its correctness proof are\n";
  out << "treated as an external dependency of this minimal project.\n";
  out << "-/\n\n";
  out << "namespace TwinPrimeExternal.GeneratedCertificate\n\n";
  out << "def firstOverflowPrime : Nat := " << c.firstOverflowRoot << "\n";
  out << "def firstOverflowSpan : Nat := " << c.firstOverflowSpan << "\n";
  out << "def firstOverflowSplitPrimes : Nat := " << c.firstOverflowSplitRoots << "\n";
  out << "def firstOverflowRoutedStarts : Nat := " << c.firstOverflowRoutedStarts << "\n";
  out << "def E_a : Nat := " << c.generatedActualEventCount << "\n";
  out << "def E_p : Nat := " << c.generatedPredictedEventCount << "\n";
  out << "def falsePredictedEventCount : Nat := "
      << c.falsePredictedEventCount << "\n\n";
  out << "theorem E_a_eq_cap :\n";
  out << "    E_a = TwinPrimeExternal.generatedMPPMCard := by\n";
  out << "  norm_num [E_a, TwinPrimeExternal.generatedMPPMCard]\n\n";
  out << "theorem E_p_eq_core :\n";
  out << "    E_p =\n";
  out << "      TwinPrimeExternal.predictedEventCount := by\n";
  out << "  norm_num [E_p,\n";
  out << "    TwinPrimeExternal.predictedEventCount]\n\n";
  out << "theorem E_p_exceeds_E_a :\n";
  out << "    E_a < E_p := by\n";
  out << "  norm_num [E_a, E_p]\n\n";
  out << "theorem core_predictedEventCount_exceeds_generatedMPPMCard :\n";
  out << "    TwinPrimeExternal.generatedMPPMCard <\n";
  out << "      TwinPrimeExternal.predictedEventCount := by\n";
  out << "  simpa [E_a_eq_cap, E_p_eq_core] using E_p_exceeds_E_a\n\n";
  out << "/--\n";
  out << "Trusted external C++ certificate theorem.\n\n";
  out << "This is the only external proof dependency in the minimal endpoint.  The C++\n";
  out << "certificate asserts that a cofinal tail of midpoint-exceptional primes would\n";
  out << "force more MP/PM events than the finite block contains.\n";
  out << "-/\n";
  out << "axiom external_no_cofinalExceptionTail :\n";
  out << "    Not (exists B,\n";
  out << "      TwinPrimeExternal.CofinalExceptionTail\n";
  out << "        TwinPrimeExternal.MidpointExceptionalPrime B)\n\n";
  out << "end TwinPrimeExternal.GeneratedCertificate\n";
}

void write_json(const std::string &path, const Certificate &c) {
  std::ofstream out(path);
  if (!out) {
    throw std::runtime_error("could not open JSON output: " + path);
  }

  out << "{\n";
  out << "  \"firstOverflowRoot\": " << c.firstOverflowRoot << ",\n";
  out << "  \"firstOverflowSpan\": " << c.firstOverflowSpan << ",\n";
  out << "  \"firstOverflowSplitRoots\": " << c.firstOverflowSplitRoots << ",\n";
  out << "  \"firstOverflowRoutedStarts\": " << c.firstOverflowRoutedStarts << ",\n";
  out << "  \"generatedActualEventCount\": " << c.generatedActualEventCount << ",\n";
  out << "  \"generatedPredictedEventCount\": " << c.generatedPredictedEventCount << ",\n";
  out << "  \"falsePredictedEventCount\": " << c.falsePredictedEventCount << "\n";
  out << "}\n";
}

}  // namespace

int main(int argc, char **argv) {
  Certificate cert;
  std::string lean_out = "TwinPrimeExternal/GeneratedCertificate.lean";
  std::string json_out;
  std::string input_json;
  bool audit = false;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "--lean-out") {
      if (++i >= argc) {
        std::cerr << "--lean-out requires a path\n";
        return 2;
      }
      lean_out = argv[i];
    } else if (arg == "--json-out") {
      if (++i >= argc) {
        std::cerr << "--json-out requires a path\n";
        return 2;
      }
      json_out = argv[i];
    } else if (arg == "--input-json") {
      if (++i >= argc) {
        std::cerr << "--input-json requires a path\n";
        return 2;
      }
      input_json = argv[i];
    } else if (arg == "--audit") {
      audit = true;
    } else {
      std::cerr << "unknown argument: " << arg << "\n";
      return 2;
    }
  }

  if (!input_json.empty()) {
    try {
      cert = read_certificate_json(input_json);
    } catch (const std::exception &ex) {
      std::cerr << ex.what() << "\n";
      return 1;
    }
  }

  if (cert.generatedPredictedEventCount <= cert.generatedActualEventCount) {
    std::cerr << "certificate does not overflow the cap\n";
    return 1;
  }

  if (audit) {
    std::cout << "firstOverflowRoot=" << cert.firstOverflowRoot << "\n";
    std::cout << "firstOverflowSpan=" << cert.firstOverflowSpan << "\n";
    std::cout << "firstOverflowSplitRoots=" << cert.firstOverflowSplitRoots << "\n";
    std::cout << "firstOverflowRoutedStarts=" << cert.firstOverflowRoutedStarts << "\n";
    std::cout << "generatedActualEventCount=" << cert.generatedActualEventCount << "\n";
    std::cout << "generatedPredictedEventCount="
              << cert.generatedPredictedEventCount << "\n";
    std::cout << "falsePredictedEventCount=" << cert.falsePredictedEventCount << "\n";
  }

  try {
    write_lean(lean_out, cert);
    if (!json_out.empty()) {
      write_json(json_out, cert);
    }
  } catch (const std::exception &ex) {
    std::cerr << ex.what() << "\n";
    return 1;
  }

  return 0;
}
